---
title: "Cornhusker Crime"
output: rmarkdown::github_document
# output: html_notebook
---


## Reefer Madness

It seems that the storm of U.S. Politic News has been unavoidable recently. The new Attorney General has been in the spotlight since his nomination. "Nevertheless, she Sen. Elizabeth Warren (D--MA) persited". Then there was the self-inforced error when he asserted that he had not been in contact with the Russians. This was in response to an objective straightforward question from Sen. Al Franken (D -- MN), during Sessions confirmation hearing. Franken's question had nothing to do with whether or not Sessions had met with anybody from Russia, or any one else for that matter. Many Dems think Sessions doth protest too much.

After his nomination to Attorny General, Sessions has wasted no time making public that the Department of Justice will be 'Tough on Crime' under his watch. In particular, he has repeatedly referenced marjijuana as an issue for this . Comparing it as "only slightly less awful", and linked to violent crime. Well, there doesn't seem to be any evidence for that assertion.


If the steady trend in states that have legalized marijuana, and national polling numbers are any indication, he seems to already be on the wrong side of history. The "War on Drugs" was not a success. This, at a time when the majority of Americans are now in favor of legalizing marijuana. [1](http://www.reuters.com/article/us-usa-drugs-report-idUSKCN12C2B8)

There are a lot of people in jail and families suffering today because of non-violent marijuana possession arrests and prosecutions. Attorney General Sessions argues that marijuana is related to violent crime. 
As a quantitative data sciency type, a recent quote struck me as questionable. The link latest quote struck me as ____. []

the "war on drugs" was a failure, with rates of drug use unchanged since President Richard Nixon launched the campaign more than 40 years ago.


```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
